### ISSUE TITLE
Default product should not be hard-coded

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#10]
When you visit the `/` page, the default product that is attempted to be loaded is `ls7_nbar_scene`.

This page should either load the first product of those available, or a list of available products to choose from perhaps.

**Comment by jeremyh** [comment]
Thanks Alex.

Closing this old issue — the current version picks the first available, starting with the defaults.

**Comment by alexgleith** [comment]
Nice work!
