### ISSUE TITLE
Large lineage/dataset YAML documents cause page load to fail

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-explorer#11]
Can be replicated using the following steps:

1. Navigate to: https://data.dea.gadevs.ga/ls7_nbar_scene
2. Select product "pq_count_summary"
3. Click "*_datasets" link in top right
4. Select first dataset from list

**Comment by jeremyh** [comment]
From my test, it loaded eventually, but was >100MB of pure HTML. The browser was extremely slow.

To fix it properly, I'll look at pushing a patch upstream to ODC: perhaps a depth limit option in the api.

**Comment by alexgleith** [comment]
Is this issue still valid, mr @GypsyBojangles ?

**Comment by GypsyBojangles** [comment]
Great question, testing here:
https://explorer.dea.ga.gov.au/dataset/9027842b-ebb4-4245-993c-41969f4f26e4
https://explorer.dea.ga.gov.au/dataset/9631913c-02a1-49be-b4d9-67f37862f725

it looks like the documents dont seem to render lineage further than parents.

They both are doing something horrible with their coordinates, but the page doesn't time out.

I would say it is fixed
