### ISSUE TITLE
Tag and Release 1.8

### ISSUE THREAD

**Issue by woodcockr** [opendatacube/datacube-explorer#116]
Alex to check on the details of what needs to be finished for 1.8 release

**Comment by alexgleith** [comment]
More info?

Explorer is already compatible with the dev branch of ODC, as that's what's being built in. Some work during the Hackathon fixed one incompatibility.

Something that _should_ be done is doing the ODC install from the PIP release of ODC 1.8.

**Comment by woodcockr** [comment]
That's exactly what the ODC SC wanted - more info!
You've provided that. The ODC SC wanted to make sure datacube-explorer was all good with the datacube-core 1.8 release. Most of us figured it was but it was suggested to check with you to make sure.
Did you want to make the PIP release change part of the 1.8 release? (note you don't need to use version 1.8, I just used that to match the datacube-core release). 

If yes, could create an ticket in this repo and add it to the 1.8 Release Project (in this repo) so the ODC SC can see its pending. 
Cheers
