### ISSUE TITLE
Explorer does not deal with non-EPSG style CRS's

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-explorer#127]
Datacube allows older metadata styles where full CRS is present in the metdata instead of the AUTHORITY:NUMERIC-CODE style explorer expects. Use backwards lookup using PyPROJ database for these. Specific case / linked to #30 

![weird_crs](https://user-images.githubusercontent.com/491396/81528629-7da16100-93a0-11ea-9ae5-2d58627ec52f.PNG)

**Comment by jeremyh** [comment]
Previous discussion in #30

**Comment by whatnick** [comment]
The product definition for this is here : https://github.com/opendatacube/datacube-dataset-config/blob/cdc050ab0044cac043531798a0149d6c95d6861e/old-prep-scripts/radiometrics_prepare.py
