### ISSUE TITLE
Enable Claire Scanner on Docker images pushed to Dockerhub

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-explorer#137]
After pushing image to Dockerhub. Pull it back down and run Claire scanner using :

https://github.com/usr42/clair-container-scan or similar.

**Comment by tom-butler** [comment]
In the past we've done this using the following script which is based off https://github.com/arminc/clair-local-scan 

```
docker run -d --name clair_db arminc/clair-db:latest
docker run -p 6060:6060 --link clair_db:postgres -d --name clair arminc/clair-local-scan:v2.0.5
clair-scanner --threshold="High" --report="clair-scan.json" --ip $(hostname -i) "$IMAGE"
```

Trivy is an alternative that seems a bit better suited to CI / CD as it doesn't require a pre-generated db of the CVEs, there are some examples of trivy github actions on the marketplace already.

**Comment by whatnick** [comment]
Trivy is way easier to use going with this one -> https://github.com/marketplace/actions/trivy-vulnerability-scanner
