### ISSUE TITLE
Root URL doesn't does not redirect consistantly

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-explorer#14]
Not sure what is causing it, but accessing the root context of web application doesnt consistantly redirect to default product.
Is it better to just have a simple landing page that is the product list?

**Comment by jeremyh** [comment]
Agreed, a landing page would be better. It currently chooses the first product with summaries available (trying the "default" products first, and then any product).

**Comment by jeremyh** [comment]
Closing: The default product can now be [set in the config file](https://github.com/opendatacube/dea-dashboard#how-can-i-configure-it).

(Adding a landing page will be a separate issue)
