### ISSUE TITLE
Explorer new theme feedback for action

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-explorer#145]
## Visual Issues
 - dataset overview on the right hand side `eo` should be `EO`
 - ~~fix dataset overview bottom white (100px padding) space~~
 - ~~need to fix `overflow: scroll` where the scroll bar is splitting the page~~
 - ~~reduce footer height, merge all footer text into one line~~
 - think about menu bar height and maybe shorten the width to allow space for map
 - remove `_` from page title and dataset name
 - ~~remove shadow from logo~~
## Link issues - broken links or misleading links
 - is there an actual navigation issue?
## Usability issues
 - ~~left-hand side date picker needs to disable month with no data~~ - > split into https://github.com/opendatacube/datacube-explorer/issues/155
 - unknown whitebox above `recenter` on the map
 - Add platform `NCI/AWS/Sandbox` information to title
 - product selector too noisy, underline + bold + italics + bold italics  white text on blue
## Feature wishlist - what links/features should be available but it is not
 - Add a `technical` section in the menu area
 - introduce animation to allow space splitting when clicked, address the issue with too much white space
## For further discussion

**Comment by omad** [comment]
Well done, huge improvement!

Not sure how you want to handle feedback, but the first thing for me is:
* lots of unnecessary scroll bars displayed in Firefox.
