### ISSUE TITLE
Cubedash-gen failures - self-intersection error for S2_L2A product

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#146]
Error is:
>Generating product summaries...
{"event":"generate.product.error","exception":"Traceback (most recent call last):\n  File \"/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1284, in _execute_context\n    cursor, statement, parameters, context\n  File \"/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py\", line 590, in do_execute\n    cursor.execute(statement, parameters)\npsycopg2.errors.InternalError_: GEOSUnaryUnion: TopologyException: Input geom 1 is invalid: Self-intersection at or near point 234823.89145728183 5518112.4330590833 at 234823.89145728183 5518112.4330590833\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/env/lib/python3.6/site-packages/cubedash/generate.py\", line 50, in generate_report\n    updated = store.get_or_update(product.name, None, None, None, force_refresh)\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_stores.py\", line 569, in get_or_update\n    force_refresh=True,\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_stores.py\", line 611, in update\n    for year_ in years\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_model.py\", line 62, in add_periods\n    periods = [p for p in periods if p is not None and p.dataset_count > 0]\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_model.py\", line 62, in <listcomp>\n    periods = [p for p in periods if p is not None and p.dataset_count > 0]\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_stores.py\", line 611, in <genexpr>\n    for year_ in years\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_stores.py\", line 569, in get_or_update\n    force_refresh=True,\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_stores.py\", line 602, in update\n    for month_ in range(1, 13)\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_model.py\", line 62, in add_periods\n    periods = [p for p in periods if p is not None and p.dataset_count > 0]\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_model.py\", line 62, in <listcomp>\n    periods = [p for p in periods if p is not None and p.dataset_count > 0]\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_stores.py\", line 602, in <genexpr>\n    for month_ in range(1, 13)\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_stores.py\", line 569, in get_or_update\n    force_refresh=True,\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_stores.py\", line 597, in update\n    product_name, _utils.as_time_range(year, month)\n  File \"/env/lib/python3.6/site-packages/cubedash/summary/_summarise.py\", line 78, in calculate_summary\n    func.now().label(\"summary_gen_time\"),\n  File \"/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2244, in execute\n    return connection.execute(statement, *multiparams, **params)\n  File \"/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1020, in execute\n    return meth(self, multiparams, params)\n  File \"/env/lib/python3.6/site-packages/sqlalchemy/sql/elements.py\", line 298, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n  File \"/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1139, in _execute_clauseelement\n    distilled_params,\n  File \"/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1324, in _execute_context\n    e, statement, parameters, cursor, context\n  File \"/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1518, in _handle_dbapi_exception\n    sqlalchemy_exception, with_traceback=exc_info[2], from_=e\n  File \"/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py\", line 178, in raise_\n    raise exception\n  File \"/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1284, in _execute_context\n    cursor, statement, parameters, context\n  File \"/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py\", line 590, in do_execute\n    cursor.execute(statement, parameters)\nsqlalchemy.exc.InternalError: (psycopg2.errors.InternalError_) GEOSUnaryUnion: TopologyException: Input geom 1 is invalid: Self-intersection at or near point 234823.89145728183 5518112.4330590833 at 234823.89145728183 5518112.4330590833\n\n[SQL: SELECT sum(srid_summaries.dataset_count) AS dataset_count, array_agg(srid_summaries.srid) AS srids, sum(srid_summaries.size_bytes) AS size_bytes, ST_AsEWKB(ST_Union(srid_summaries.footprint_geometry)) AS footprint_geometry, max(srid_summaries.newest_dataset_creation_time) AS newest_dataset_creation_time, now() AS summary_gen_time \nFROM (SELECT ST_SRID(cubedash.dataset_spatial.footprint) AS srid, count(*) AS dataset_count, ST_Transform(ST_Union(cubedash.dataset_spatial.footprint), %(ST_Transform_1)s) AS footprint_geometry, sum(cubedash.dataset_spatial.size_bytes) AS size_bytes, max(cubedash.dataset_spatial.creation_time) AS newest_dataset_creation_time \nFROM cubedash.dataset_spatial \nWHERE (tstzrange(%(tstzrange_1)s, %(tstzrange_2)s, %(tstzrange_3)s) @> cubedash.dataset_spatial.center_time) AND cubedash.dataset_spatial.dataset_type_ref = (SELECT agdc.dataset_type.id \nFROM agdc.dataset_type \nWHERE agdc.dataset_type.name = %(name_1)s) GROUP BY srid) AS srid_summaries]\n[parameters: {'ST_Transform_1': 3577, 'tstzrange_1': datetime.datetime(2020, 6, 1, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/Australia/Darwin')), 'tstzrange_2': datetime.datetime(2020, 7, 1, 0, 0, tzinfo=tzfile('/usr/share/zoneinfo/Australia/Darwin')), 'tstzrange_3': '[]', 'name_1': 's2_l2a'}]\n(Background on this error at: http://sqlalche.me/e/2j85)","level":"exception","product":"s2_l2a","timestamp":"2020-06-23T02:18:26.815106Z"}
s2_l2a error (see log)
done. 0/1 generated, 1 failures

Part of the issue is being unable to easily track down the dataset causing the issue.

**Comment by alexgleith** [comment]
Turns out the issue was related to scenes crossing the anti-meridian. So while I didn't fix the underlying cause, I was able to resolve the issue with a workaround.

**Comment by jeremyh** [comment]
This may have been fixed with the move to ODC's own anti-meridian handling (and I haven't seen it in my db clones). Reopen if you see it again on the new release.

**Comment by omad** [comment]
This is old, it sounds like it's probably fixed. Closing.
