### ISSUE TITLE
upgrade code to current werkzurg

### ISSUE THREAD

**Issue by uchchwhash** [opendatacube/datacube-explorer#147]
- werkzurg 1.0.1 has moved `werkzurg.cached_property` to `werkzurk.utils.cached_property`

**Comment by jeremyh** [comment]
Thanks for the report Imam

Did you get a stacktrace/error for this? We don't use `werkzurg` directly -- I assume it's one of our dependencies

**Comment by uchchwhash** [comment]
I believe this is resolved now.
