### ISSUE TITLE
Global navigation is not obvious enough

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-explorer#163]
The URLs of Explorer have a clear hierarchy and layout, with several section and sub-sections, but few people navigate  via typing URLs.

On pages themselves, there's no visual indication (global menu, tabs, breadcrumbs, styling, etc) to indicate clearly what section the user is in, or where they can go to. We should make this less of a treasure-hunt.

**Comment by pindge** [comment]
This can stay open, we are not sure how well the menus will be received
