### ISSUE TITLE
The latest changes slow down explorer bootup

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-explorer#178]
While running in Kubernetes / Containerized environments with deadlines on application startup explorer fails to start within a minute or so of allocated time against large (20+ million dataset) datacube. This causes containers to be terminated and application getting stuck in reboot loop. Less prepare work / caching during application start can help here. 

Also would need some estimates on application startup given RAM / CPU limited containers would be useful.

**Comment by jeremyh** [comment]
A minute, wow?  Something significant is wrong -- It takes a second to boot locally on a full clone of the NCI DB. I don't believe any of the changes added any new code to startup. I wonder if it's timing out trying to connect to something in the environment -- the DB, or Sentry or something?

It would be useful if we could run something like pyspy on it to see where it's blocked.

**Comment by whatnick** [comment]
Thanks for the check at your end. We will attempt to instrument as much as we can to check.
