### ISSUE TITLE
STAC API is incompatible with reference implementations

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#181]
For an example, this works: `https://explorer.digitalearth.africa/stac/search?limit=10&product=s2_l2a` but this doesn't `https://explorer.digitalearth.africa/stac/search?limit=10&collection=s2_l2a`.

We should be supporting STAC terminology here, and not ODC terms.

I think the reference implementation is: https://github.com/stac-utils/stac-server

This is a live implementation: https://earth-search.aws.element84.com/v0/

Possibly we should test against the STAC Validator listed here: https://github.com/alexgleith/community-sprints/blob/6593b05bba6c06266d3b39b8821a892d218861dc/08182020-remote/software/progress.md#stac-validator

**Comment by omad** [comment]
This issue is so old I strongly suspect it's been resolved and is no longer relevant. STAC support has been added and tested.
