### ISSUE TITLE
The /audit/storage page is slow to load on dev

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-explorer#201]
My guess is that this is due to the number of product-location queries.  They're done for every row of the table, so it's an NxM query situation. On my local machine, with near-zero latency to local database per-query, it's quite fast to load. 

<sup>(this is all a guess, of course we should measure)</sup>

Those calculations could be cached heavily as they're the same for everybody, don't change often, and are only estimates anyway (based on a tiny sample).

**Comment by jeremyh** [comment]
Alternative option: pre-calculate them ahead of time in summary generation. It could then be an exact answer, rather than an estimate.

**Comment by omad** [comment]
Between #268 and increasing the cache duration, this is probably no longer an issue. Closing.
