### ISSUE TITLE
Footprint CRS is hardcoded

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#206]
This really shouldn't be a region-centric CRS, as footprints away from Australia are likely to be quite distorted.

https://github.com/opendatacube/datacube-explorer/blob/17d840aa35d4fdd11a594777589cd2a29cc86444/cubedash/summary/_schema.py#L40

**Comment by jeremyh** [comment]
The tricky thing is that CRS is included in the PostGIS column definition, so it's a global static value along with the tables themselves. 

I was experimenting a few months ago with removing the value and only setting it when we do a new explorer schema `init`, though it's not the cleanest solution: https://github.com/opendatacube/datacube-explorer/commit/8d202e11e1753f074b2dfb7fe39335be56f855b7

**Comment by JonDHo** [comment]
We are getting this issue very often in Latin America with broken footprints (particularly over Brazil). One thought is whether the "Equal Earth" projection might suit as a global default.

See:
- http://equal-earth.com/equal-earth-projection.html
- https://proj.org/operations/projections/eqearth.html

As you can see, this is now in Proj, but it isn't yet in PostGIS by default, but there are examples of using it, e.g. https://gist.github.com/makella/ebdd0c7510c94386531fd61397cbb8d4

This appears (initially) to be a viable option for a global equal area projection, but will need to be injected into PostGIS as well as per the link above:
```sql
INSERT INTO 
  "spatial_ref_sys" ("srid","auth_name","auth_srid","srtext","proj4text") 
VALUES 
  (8857,'EPSG',8857,'','+proj=eqearth +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs')
```

See also:
https://pro.arcgis.com/en/pro-app/latest/help/mapping/properties/equal-earth.htm
and the comparison of different projections here: https://www.arcgis.com/sharing/rest/content/items/e8b85d508d2c4f21a3dec4e52dc7d9c4/data

It also exists in QGS by default.

**Comment by alexgleith** [comment]
Since it's only used for internal representation, I think it would be better to use an existing CRS.

My suggestion is either WGS84 `epsg:4326` or this equal area crs `epsg:6933`.

I do think it's worth changing this...

**Comment by JonDHo** [comment]
If there is no need for sticking with an equal area projection, then even a hard-coded change to something global (4326, 6933 or 3857) would be an immediate change which makes explorer globally suitable. A proper configurable fix of course would be ideal, but a hard-coded global fix would still be useful.

**Comment by jeremyh** [comment]
Added in #328 -- allows one to select a CRS on init of the schema, and it defaults to 6933.
