### ISSUE TITLE
NCI VDI deployment requires new/refreshed timeline.json files

### ISSUE THREAD

**Issue by mpaget** [opendatacube/datacube-explorer#23]
On VDI, dashboard doesn’t load because the following files do not exist,
/g/data/v10/public/agdc-v2-dashboard/product-summaries/*/timeline.json for:
- ls5_pq_albers
- ls7_nbar_albers
- ls7_nbart_albers
- (ls5_fc_albers_archived too but maybe not needed for dashboard to work)

All other products have timeline.json files.

This creates an error irrespective of which product is requested in the dashboard. For example when requesting http://127.0.0.1:8080/ls8_nbart_albers:

[2018-09-06 13:22:11,197] ERROR in app: Exception on /ls8_nbart_albers [GET]
Traceback (most recent call last):
....
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/v10/public/agdc-v2-dashboard/product-summaries/ls5_pq_albers/timeline.json'
127.0.0.1 - - [06/Sep/2018 13:22:11] "GET /ls8_nbart_albers HTTP/1.1" 500 -

Propose that the timeline.json files be refreshed (if required) and the three missing ones added, please.

**Comment by jeremyh** [comment]
Thanks Matt.

The NCI collection is now visible externally from https://data.dea.gadevs.ga

I'm going to retire the VDI directions. Users running their own instances (often on the same VDI host) has many small gotchas, and doesn't take advantage of any shared caching.

**Comment by mpaget** [comment]
Good stuff. Thank you.
