### ISSUE TITLE
Feature Request : Publish Explorer via PyPI

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-explorer#270]
Explorer already has a clearly defined set of production, testing and development dependencies in setup.py. Leverage this list to publish it as python wheel / source package on PyPI.

**Comment by jeremyh** [comment]
I just tried doing this, but it looks like it's blocked by our usage of a direct (Git) dependency on `flask_themes`: https://github.com/opendatacube/datacube-explorer/blob/90c131368121af040d63618b426d031092880cee/setup.py#L65

**Comment by jeremyh** [comment]
Perhaps investigate moving to something more maintained, like [flask-themer](https://pypi.org/project/flask-themer/)* 

*this is not an endorsement; it was just the first okay-sounding one on a Google search

**Comment by jeremyh** [comment]
Now installable from pypi :tada:  https://github.com/opendatacube/datacube-explorer/releases/tag/2.6.0
