### ISSUE TITLE
importlib-metadata wrong version?

### ISSUE THREAD

**Issue by jonas-eberle** [opendatacube/datacube-explorer#277]
Hi all, 

I tested to start the datacube-explorer with docker-compose. The flask application could successfully been started, but an error was shown on the website because the cubedash-gen commands have not been conducted (e.g., please run `cubedash-gen --init`). 

I tried to run these commands within the running docker container, but got the following error: 

`root@098aa300025e:/code# cubedash-gen -v --init`
`Traceback (most recent call last):`
`  File "/env/bin/cubedash-gen", line 33, in <module>`
`    sys.exit(load_entry_point('datacube-explorer', 'console_scripts', 'cubedash-gen')())`
`  File "/env/bin/cubedash-gen", line 22, in importlib_load_entry_point`
`    for entry_point in distribution(dist_name).entry_points`
`  File "/env/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 833, in distribution`
`    return Distribution.from_name(distribution_name)`
`  File "/env/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 448, in from_name`
`    raise PackageNotFoundError(name)`
`importlib_metadata.PackageNotFoundError: No package metadata was found for datacube-explorer`

I discovered an error within the docker-compose build process 
`pyppeteer 0.2.5 requires importlib-metadata<3.0.0,>=2.1.1; python_version < "3.8", but you'll have importlib-metadata 3.10.1 which is incompatible.`

With installing importlib-metadata with version 2.1.1 I could reinstall the datacube-explorer application (`python setup.py develop`) in the container. Afterwards I was able to use cubedash-gen within the container and run the following commands:
`cubedash-gen -v --init`
`python -m cubedash.generate --all`

**Comment by jeremyh** [comment]
Thanks for the report Jonas.

Oddly, I just checked my own container and I'm running the the "wrong" version of importlib_metadata (3.10.1). I'm wonder if something deeper happened -- it looks like Explorer's package may not have been installed at all.  But I haven't been able to reproduce the issue yet. 

I had planned to look at freezing our dependencies in the container to avoid quirks like this, as new releases of anything can break our build at unexpected times.
