### ISSUE TITLE
"About Products" page is missing a / in the s3:// protocol

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#279]
Pages like this: https://explorer.dev.digitalearth.africa/audit/storage

Have a location like this: `s3:/deafrica-input-datasets/alos_palsar_mosaic/2018`

I think it should be like this `s3://deafrica-input-datasets/alos_palsar_mosaic/2018`

**Comment by jeremyh** [comment]
Fixed in 2.8.1
