### ISSUE TITLE
Cubedash init on indexed sentinel data gives SQL error

### ISSUE THREAD

**Issue by diplonics** [opendatacube/datacube-explorer#293]
Following SQL is causing an error when trying to initialise the data explorer with Sentinel data recently indexed in our ODC:

SELECT every(sampled_dataset.id = 'fa0f7f70-8937-4ce0-b23c-92d0b1639664') AS id, 
 every(agdc.common_timestamp((sampled_dataset.metadata #>> '{creation_dt}')) = datetime.datetime(2020, 10, 2, 21, 54, 42, 845000, tzinfo=datetime.timezone.utc)) AS creation_time, 
 every((sampled_dataset.metadata #>> '{format, name}') = 'GeoTIFF') AS format, 
 every((sampled_dataset.metadata #>> '{ga_label}') IS NULL) AS label, 
 every((sampled_dataset.metadata #>> '{platform, code}') = 'Sentinel-2A') AS platform, 
 every((sampled_dataset.metadata #>> '{instrument, name}') = 'MSI') AS instrument, 
 every((sampled_dataset.metadata #>> '{product_type}') = 'S2MSI2A') AS product_type FROM agdc.dataset 
 TABLESAMPLE system(69.589422407794) AS sampled_dataset WHERE sampled_dataset.dataset_type_ref = 82 AND sampled_dataset.archived IS NULL;

The error is a syntax error as follows:
ERROR:  syntax error at or near "AS"
LINE 8:  TABLESAMPLE system(69.589422407794) AS sampled_dataset WHER...

So the SQL is not even being run but I can't spot the syntax issue...any help welcome.

I'm using this command to initialise the environment which is causing the issue:
cubedash-gen --init --all -v -v --event-log-file odclog.log

Possible we have some data issues in the in the ODC itself but not getting errors from any of the core ODC index processes..

**Comment by n0bitann** [comment]
I got same error with opendatacube version 1.8.3  when I try to  cubedash-gen --init --all with large ingested data

**Comment by diplonics** [comment]
This was being run on 2 years worth of sentinel data that was indexed in our ODC.
For the Explorer UI this data would only show up in the 'recently added' section after we ran the cubedash-gen --inti --all and the reported error was output...
However, his seemed to sort itself out within 24 hours!!!!
The Explorer UI had registered the data properly and all was okay as the auto-summary update process must have picked up the issues and sorted things out...

**Comment by jeremyh** [comment]
Thanks for the reports @diplonics and @Jetzika. I can reproduce it locally by upgrading sqlalchemy (sqlalchemy generates most of our sql statements)

For now, you can work around the issue by going back to the previous version of sqlalchemy:

```
pip install sqlalchemy==1.3.24
```

**Comment by jeremyh** [comment]
Fixed in dev build: #296
