### ISSUE TITLE
If there's a thumbnail or overview or quicklook, add it to the leaflet view for the dataset page

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#297]
How to add it: https://leafletjs.com/reference-1.7.1.html#imageoverlay

How to identify it? Not sure.

Essentially we should be able to add an image to this kind of page, where the blue area is. https://explorer.digitalearth.africa/products/ls8_sr/datasets/0602918d-63e1-597c-87e9-f9b7a68e2a1a

![image](https://user-images.githubusercontent.com/3445853/124847101-8bbb3380-dfdd-11eb-8cf5-650a4ae5a3fb.png)

**Comment by robbibt** [comment]
I think we can close this now thanks to @Ariana-B - check out this @alexgleith!
https://explorer.dev.dea.ga.gov.au/products/ga_s2bm_ard_3/datasets/3e17a61a-c03b-46da-a517-54be3e5ebc21

**Comment by robbibt** [comment]
I think we can close this now thanks to @Ariana-B - check out this @alexgleith!
https://explorer.dev.dea.ga.gov.au/products/ga_s2bm_ard_3/datasets/3e17a61a-c03b-46da-a517-54be3e5ebc21

**Comment by alexgleith** [comment]
Woohoo, that's awesome! Well done @Ariana-B!

Looks great. Only suggestion I have is getting rid of the clicky finger 👆 when you mouseover the polygon... probably needs a new issue :-) 

![image](https://user-images.githubusercontent.com/3445853/205810565-d9516afd-137f-4f33-bdfc-6282050ba805.png)

**Comment by robbibt** [comment]
> Woohoo, that's awesome! Well done @Ariana-B!
> 
> Looks great. Only suggestion I have is getting rid of the clicky finger 👆 when you mouseover the polygon... probably needs a new issue :-)
> 
> ![image](https://user-images.githubusercontent.com/3445853/205810565-d9516afd-137f-4f33-bdfc-6282050ba805.png)

Yeah, or make it download the thumbnail file when you click on it so you can open it up for a closer look...
