### ISSUE TITLE
Ancillary data and potentially other links all go to the same place

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#301]
On the data page, like this one: https://explorer.digitalearth.africa/products/s2_l2a/datasets/6b886b97-d5f2-5529-85a7-6aaecfd3e93a

Data and ancillary data links are assumed to all go to the same place, i.e., the base URI is the same for all.

As shown in this document: https://deafrica-sentinel-2.s3.af-south-1.amazonaws.com/sentinel-s2-l2a-cogs/36/N/VH/2021/7/S2B_36NVH_20210708_0_L2A/S2B_36NVH_20210708_0_L2A.json

Some links are to S3 and others are HTTPS. The HTTPS links should NOT be changed to point to S3.

Example links:

```Javascript
    "visual": {
      "href": "s3://deafrica-sentinel-2/sentinel-s2-l2a-cogs/36/N/VH/2021/7/S2B_36NVH_20210708_0_L2A/TCI.tif",
      "type": "image/tiff; application=geotiff; profile=cloud-optimized",
      "title": "True color image",
      "gsd": 10,
      "eo:bands": [
        {
          "name": "B04",
          "common_name": "red",
          "center_wavelength": 0.6645,
          "full_width_half_max": 0.038
        },
        {
          "name": "B03",
          "common_name": "green",
          "center_wavelength": 0.56,
          "full_width_half_max": 0.045
        },
        {
          "name": "B02",
          "common_name": "blue",
          "center_wavelength": 0.4966,
          "full_width_half_max": 0.098
        }
      ],
      "proj:shape": [
        10980,
        10980
      ],
      "proj:transform": [
        10.0,
        0.0,
        399960.0,
        0.0,
        -10.0,
        300000.0,
        0.0,
        0.0,
        1.0
      ],
      "roles": [
        "overview"
      ]
    },
    "B01": {
      "href": "s3://deafrica-sentinel-2/sentinel-s2-l2a-cogs/36/N/VH/2021/7/S2B_36NVH_20210708_0_L2A/B01.tif",
      "type": "image/tiff; application=geotiff; profile=cloud-optimized",
      "title": "Band 1 (coastal)",
      "gsd": 60,
      "eo:bands": [
        {
          "name": "B01",
          "common_name": "coastal",
          "center_wavelength": 0.4439,
          "full_width_half_max": 0.027
        }
      ],
      "proj:shape": [
        1830,
        1830
      ],
      "proj:transform": [
        60.0,
        0.0,
        399960.0,
        0.0,
        -60.0,
        300000.0,
        0.0,
        0.0,
        1.0
      ],
      "roles": [
        "data"
      ]
    },
```

**Comment by jeremyh** [comment]
(I missed this issue before.)

I don't think Explorer is changing these paths.

From looking at the [raw ODC document](https://explorer.digitalearth.africa/dataset/6b886b97-d5f2-5529-85a7-6aaecfd3e93a.odc-metadata.yaml), they're indexed with one single `s3://` location:

```yaml
location: s3://deafrica-sentinel-2/sentinel-s2-l2a-cogs/36/N/VH/2021/7/S2B_36NVH_20210708_0_L2A/S2B_36NVH_20210708_0_L2A.json
```
... and all measurement paths are relative:
```yaml
  AOT:
    grid: g60m
    path: AOT.tif
  B01:
    grid: g60m
    path: B01.tif
```

So Explorer seems to be correctly representing what's indexed in the ODC.

I think it's the indexer that is stripping these prefixes: [in the odc-tools repo](https://github.com/opendatacube/odc-tools/blob/a23cd1665fb536792ecf57ad7b214a8ea2c3fabd/libs/stac/odc/stac/transform.py#L149-L154), the "relative" option pulls out the filename without checking if the prefix is the same as others:

```python
    def _get_path(asset):
        path = asset["href"]
        if relative:
            path = Path(path).name

        return path
```

A similar function is in eodatasets here, which does fall back to absolute paths if it cannot be made _validly_ relative: https://github.com/opendatacube/eo-datasets/blob/e45d00c78496683ca09902f66dd23007db61f355/eodatasets3/assemble.py#L1025-L1069

**Comment by alexgleith** [comment]
I think this will be fixed with this change. Sorry it took me so long to do!

https://github.com/opendatacube/odc-tools/pull/467

**Comment by alexgleith** [comment]
Confirmed fixed :-)
