### ISSUE TITLE
Set up integration tests using PySTAC Client or a similar tool

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#304]
[PySTAC Client](https://github.com/stac-utils/pystac-client) can be used to consume a STAC API.

It would be wonderful if Explorer had tests that ensured that it conforms with the API.

Can we discuss?

**Comment by jeremyh** [comment]
Yes, good idea. I’m working on a branch with stac 1.0.0 updates and might include it there

**Comment by alexgleith** [comment]
Awesome!

**Comment by alexgleith** [comment]
FYI, I have indexing off a STAC API working in a generic way in odc-tools, so hopefully we can get it working off Explorer soon. Building new datacubes from old datacubes!

**Comment by omad** [comment]
There look to be fairly comprehensive STAC tests in [integration_tests/test_stac.py](https://github.com/opendatacube/datacube-explorer/blob/develop/integration_tests/test_stac.py), closing.
