### ISSUE TITLE
cannot install 2.5.4 version 

### ISSUE THREAD

**Issue by mariembensalem** [opendatacube/datacube-explorer#306]
when I try to install datacube-explorer v2.5.4 after extract it to a directory, enter the directory, and pip install . I have this error 
![1](https://user-images.githubusercontent.com/83786015/128570882-d8e2fd48-67f4-435f-a1ba-6ab35d5ab577.png)
![2](https://user-images.githubusercontent.com/83786015/128570886-03e0c9f9-2fb9-4dc4-b1b3-03d18f442fe9.png)

**Comment by jeremyh** [comment]
Closing, as we corresponded on Stack Exchange instead: https://gis.stackexchange.com/questions/408194/cannot-install-datacube-explorer-2-5-4-version/408378#408378
