### ISSUE TITLE
Enable region code in hover text

### ISSUE THREAD

**Issue by simonaoliver** [opendatacube/datacube-explorer#313]
For consideration - Region code (eg. Landsat WRS or Sentinel 2 MGRS reference etc.) shows as bottom right - eg. https://explorer.digitalearth.africa/products/s2_l2a/extents , though the page extent requires the user to use right hand scroll bar to move the bottom of the page to access it (depending on screen dims etc.). It may be more convenient for a user if hover text were added containing the region code on the cursor and / or defaults to enable full map view including region code / dataset count display.

**Comment by jeremyh** [comment]
Thanks. Added in #314
