### ISSUE TITLE
Landsat Path Row Handling Error

### ISSUE THREAD

**Issue by ASVincent** [opendatacube/datacube-explorer#33]
There are a couple of minor issues when a user directory inputs path row into the url. 

Example 1: Leading zeroes:
`{{hostname}}/region/ls8_nbar_scene/096_071`
When leading zeroes are including in the path row reference the area is correctly identified on the map provided but no datasets are returned on the page; this may occur if a user copies and pastes path row values from a set with leading zeroes.

Example 2: Invalid Path Rows
`{{hostname}}/region/ls8_nbar_scene/10096_10071`
If a user inputs invalid path row values for a given dataset cubedash responds with an internal server error; this may crop up if a user is copy-pasting into the URL without paying attention; or where multiple collections with different spatial models are provided from one instance.

**Comment by pindge** [comment]
Cannot replicate
