### ISSUE TITLE
Incorrect tile numbers displayed for DEA C3 summary products

### ISSUE THREAD

**Issue by GypsyBojangles** [opendatacube/datacube-explorer#342]
The DEA C3 summary product grid,  [defined here](https://docs.dea.ga.gov.au/reference/collection_3_summary_grid.html) is not being correctly represented within the explorer map UI [example here](https://explorer.dev.dea.ga.gov.au/products/ga_ls_wo_fq_nov_mar_3/extents)
Clicking on the tile in the top left (Tile -17, -11) you are actually accessing tile x11y46 [shown here](https://explorer.dev.dea.ga.gov.au/product/ga_ls_wo_fq_nov_mar_3/regions/-17_-11)

This tile index is being infered from the product storage information, which be believe to be correct [here](https://explorer.dev.dea.ga.gov.au/products/ga_ls_wo_fq_nov_mar_3) not from the dataset region code (or equivalent) [visible here](https://explorer.dev.dea.ga.gov.au/products/ga_ls_wo_fq_nov_mar_3/datasets/94594ba3-ecf6-4894-9825-5b985d260dda)

**Comment by pindge** [comment]
@jeremyh, I am setting up a pr for testing this section, is there a specific product that you can think of that led to the decision to place `GridRegionInfo` to be the first in the `if` statement?

https://github.com/opendatacube/datacube-explorer/blob/6f861c364a0ce5e35516330b60090e7275397aa7/cubedash/summary/_extents.py#L696-L704

**Comment by pindge** [comment]
This issue is also impacting digitalearth africa explorer instance, i.e. https://explorer.digitalearth.africa/product/gm_ls5_ls7_annual/regions/-135_1365, explorer recorded the region as `-135_1365`, but the region from metadata is `x176y122`
