### ISSUE TITLE
Dataset titles/labels in Explorer

### ISSUE THREAD

**Issue by ghost** [opendatacube/datacube-explorer#391]
Hi,

What is the intended way to control the displayed label/title of datasets when indexing from STAC documents (using `s3-to-dc --stac`)? Currently, all datasets are labeled by the filename of the STAC document. Unfortunately for us, this means all datasets are called the same thing.

Is this something we can change in Explorer, or is it an effect of the STAC-to-EO3 conversion?

This is what it looks like in Explorer:

![20220614T000712](https://user-images.githubusercontent.com/44668428/173526195-b51b94f3-f5bc-409e-9bca-eafeacd0a17f.png)

Here's a snippet from the STAC document itself:

![20220614T100616](https://user-images.githubusercontent.com/44668428/173527180-bdcaf926-ba45-4d82-bb68-485a8f2581d6.png)

**Comment by pindge** [comment]
Hi,

I have included the chain of code that is responsible for displaying the label, the metadata definition required is `label` as per https://github.com/opendatacube/datacube-explorer/blob/322086297110396fb162853f69661c245ab71611/cubedash/_utils.py#L131

Here is a working example we host in Digitalearth Australia program: https://explorer-aws.dea.ga.gov.au/products/ga_ls7e_ard_3/datasets


https://github.com/opendatacube/datacube-explorer/blob/322086297110396fb162853f69661c245ab71611/cubedash/templates/search.html#L120

https://github.com/opendatacube/datacube-explorer/blob/ab2e114e779ceb12eefa2bc7712b33ffa6f662ef/cubedash/_filters.py#L44-L51

https://github.com/opendatacube/datacube-explorer/blob/322086297110396fb162853f69661c245ab71611/cubedash/_utils.py#L125-L142

**Comment by ghost** [comment]
Thank you. It appears the issue is not with Explorer. I will need to look into why the `label` field is not generated for us when indexing from our STAC documents.

**Comment by omad** [comment]
Answered. Closing. May require an issue against https://github.com/opendatacube/odc-tools , but would need more information.
