### ISSUE TITLE
Question regarding conversion of asset links to AWS urls

### ISSUE THREAD

**Issue by ghost** [opendatacube/datacube-explorer#392]
How do I stop Explorer from converting my `s3://bucket/path/to/key` asset links to AWS urls?

I have set `CUBEDASH_DATA_S3_REGION=None`, but this seems to have no effect.

Preferably, we'd want to be able to point to our own domain, something like `https://s3.domain.com/bucket/path/to/key`. However, just leaving the `s3://` links untouched also works. Since our datasets are stored on a Ceph cluster on-prem, we don't want our users to be redirected to AWS. 

Thanks!

**Comment by pindge** [comment]
This refers to the location link displayed on explorer individual dataset page, i.e. https://explorer-aws.dea.ga.gov.au/products/ga_ls7e_ard_3/datasets/07624194-c854-42e2-9c08-d8e498d39b41

![image](https://user-images.githubusercontent.com/24644475/173715722-f1fbce4c-4051-46ba-b4a7-8baf815127fe.png)
which is different to it's hovered anchor link 
![image](https://user-images.githubusercontent.com/24644475/173715819-7b253de6-f84c-44ba-a623-f232f9472ff8.png)

**Comment by pindge** [comment]
The code that is responsible for this are

https://github.com/opendatacube/datacube-explorer/blob/bf1c8c8b183743c308366197adb25a8fd555fa26/cubedash/templates/dataset.html#L131

https://github.com/opendatacube/datacube-explorer/blob/ab2e114e779ceb12eefa2bc7712b33ffa6f662ef/cubedash/_filters.py#L114-L116

https://github.com/opendatacube/datacube-explorer/blob/a989a8eb622589cc8d35c10edaae5b2df268065c/cubedash/_utils.py#L124-L153

**Comment by pindge** [comment]
as per pr #393 test cases, could you please check if the `app.config` is set correctly? happy to be pinged on slack
