### ISSUE TITLE
Explorer needs a readthedoc site

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-explorer#425]
There are many app configurations that needs to be explained in full detail, the current readme isn't sufficient

**Comment by omad** [comment]
Hiya Pin,
I'm happy to help with this! I think as a first attempt we should add some better structure to the readme, and maybe later think about setting up a full documentation site.

**Comment by omad** [comment]
Lets leave this open until the documentation site actually exists. :)

**Comment by pindge** [comment]
> Hiya Pin, I'm happy to help with this! I think as a first attempt we should add some better structure to the readme, and maybe later think about setting up a full documentation site.

I absolutely need help with it. its failing https://readthedocs.org/projects/datacube-explorer/builds/18106400/
