### ISSUE TITLE
Remove dependency on the `digitalearthau` package

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-explorer#472]
We currently depend on the [digitalearthau package](https://github.com/GeoscienceAustralia/digitalearthau/) for running the test suite. This package is not publicly available from PyPI or conda-forge, and contains lots of code that is no longer actively used. Also, this test fixture code is not compatible with  [datacube-core](https://github.com/opendatacube/datacube-core/) >= 1.8.8 (See #453). 
We need to remove this dependency. 

The test functions are useful for setting up and cleaning up an ODC database.

The easiest solution is probably to copy that code into this repository.

The best solution would be to move that code into [datacube-core](https://github.com/opendatacube/datacube-core/) and have **it** provide test fixtures for ODC databases.

@jeremyh @Ariana-B @SpacemanPaul @pindge

**Comment by pindge** [comment]
related to : 
https://github.com/opendatacube/datacube-explorer/issues/375
and
https://github.com/opendatacube/datacube-core/issues/1274

**Comment by omad** [comment]
Fixed in #490
