### ISSUE TITLE
Expose datasets and search using the STAC API

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-explorer#48]
This can be based on existing code for translating _ODC YAML_ documents into _Static STAC Items_ and _Catalogs_. See the [reference STAC Specification](https://github.com/radiantearth/stac-spec/) for more details.

Development seed has a [documented example implementation of the STAC API](https://sharkinsspatial.github.io/sat_api_docs/?python#the-sat-api.)

**Comment by alexgleith** [comment]
This has been done
