### ISSUE TITLE
Helm Chart Deployment Doesn't Reload Configuration Changes

### ISSUE THREAD

**Issue by omad** [opendatacube/datacube-explorer#495]
When I deploy a new version version of the Explorer helm chart with an updated configuration, I expect the Deployment to be restarted with the new configuration. But this does not happen.

I think the reason is that the Explorer Helm chart sets up a ConfigMap containing a `settings.env.py`  file, which is mounted into the running Pods. ConfigMap mounts can be updated dynamically, without restarting the Pods, but Datacube Explorer doesn't seems to support live reloading of it's configuration when a file changes.

**Comment by mpaget** [comment]
> Datacube Explorer doesn't seems to support live reloading of it's configuration when a file changes

I think this is a feature of gunicorn.

```bash
# Send a `HUP` signal to the gunicorn master to reload the Flask configuration
# See https://docs.gunicorn.org/en/stable/signals.html#master-process
ps -ef | grep gunicorn  # Get the process ID for "gunicorn: master [cubedash:app]"
kill -HUP $PID  # Send the signal
```

**Comment by pindge** [comment]
Its the limitation of Kubernetes deployment, the potential solution here: https://github.com/stakater/Reloader

**Comment by pindge** [comment]
https://github.com/opendatacube/datacube-charts/blob/master/stable/datacube-explorer/templates/deployment.yaml#L24-L27

https://github.com/helm/helm/issues/2639

setting `checksum` could solve this
