### ISSUE TITLE
Explorer "fields" section hidden from view

### ISSUE THREAD

**Issue by robbibt** [opendatacube/datacube-explorer#508]
On dev Explorer, the "Fields" section includes metadata fields that are hidden until you hover over them:
https://explorer.dev.dea.ga.gov.au/products/ga_ls8c_ard_3/datasets/3a9a61f1-80ef-471b-a244-9a7e1b07fb93

![image](https://user-images.githubusercontent.com/17680388/207227077-a4bba3c6-ace8-4f3f-a5bc-d3e7ac3c3490.png)

I suspect only the magnifying glass icon is meant to be hidden, not the text itself. 

Looks like this was changed in the PR below:
https://github.com/opendatacube/datacube-explorer/pull/505/files

**Comment by robbibt** [comment]
Also out of interest: why do these fields not link to the search page? They feel like useful things that users might want to search by, just like the other metadata

```
instrument
platform 
product_family
```

**Comment by Ariana-B** [comment]
> Also out of interest: why do these fields not link to the search page? They feel like useful things that users might want to search by, just like the other metadata
> 
> ```
> instrument
> platform 
> product_family
> ```

Any fields that don't link to a search page are fields that are not searchable for that product. You'll notice that instruct, platform, and product_family aren't present in the search page drop-down select menu either.
