### ISSUE TITLE
Clicking on a Dataset in the Map View will open an incorrect URL if SCRIPT_NAME is set

### ISSUE THREAD

**Issue by roarmstrong** [opendatacube/datacube-explorer#51]
In 2.0.9

Steps to reproduce:
- Navigate to https://ows.services.devkube.dea.ga.gov.au/dashboard/historical_airborne_photography
- Switch to Datasets view
- Click on the Dataset in the map
- Will encounter a 404 error message. Web page is https://ows.services.devkube.dea.ga.gov.au/dataset/d486cce1-837e-4a41-8e2a-c2ca42a94749 which is missing "/dashboard"
- https://ows.services.devkube.dea.ga.gov.au/dashboard/dataset/d486cce1-837e-4a41-8e2a-c2ca42a94749 does work as excepted

This appears to be related to:
https://github.com/opendatacube/datacube-explorer/blob/ee25003e5f25ca6edc35bacb7235cc2963a384d0/cubedash/static/overview.js#L217
https://github.com/opendatacube/datacube-explorer/blob/ee25003e5f25ca6edc35bacb7235cc2963a384d0/cubedash/static/overview.ts#L224

Where the URL generated for onclick does not use Flask to get the url for the page and will ignore `SCRIPT_NAME` if set.

**Comment by jeremyh** [comment]
Thanks Robbie!

Fixed in #53, which is in release 2.1.0
