### ISSUE TITLE
Latest revision of docker image does not service http requests

### ISSUE THREAD

**Issue by santoshamohan** [opendatacube/datacube-explorer#67]
## Issue: 
The latest revision of `cubedash` app fails to serve any `http` / `https` requests coming from `alb` load balancer.

Last know working docker image is `v2.1.0`.

**Comment by alexgleith** [comment]
Hey Santosh, what isn't working with this?

I ran the Docker image with `docker run --rm -p 80:8080 opendatacube/dashboard:latest` and this worked fine. 

Is it using a different port than expected, perhaps?

**Comment by santoshamohan** [comment]
Issue no longer seen on the latest docker image.
