### ISSUE TITLE
(finish implementing) incremental-update of summaries

### ISSUE THREAD

**Issue by jeremyh** [opendatacube/datacube-explorer#68]
Currently there's no easy way to update cubedash's product summaries once created.

There is a max_age when the spatial table is updated, but not when generating the summaries themselves, so they are skipped if they exist at all (in the `get_or_update()` function).

We should extend the generate command to allow updating summaries older than a certain age.

(this was never needed previously in the NCI instance as it has a freshly-cloned database every day)

Reported by @dunkgray, as this affected DEA Africa.

**Comment by alexgleith** [comment]
Fixed in: https://github.com/opendatacube/datacube-explorer/pull/84

**Comment by jeremyh** [comment]
Reopening this — we only have a “force” option to force recreation of every summary,  but I’d like to add real incremental updates.
