### ISSUE TITLE
Include number of 'clear' pixels in dashboard

### ISSUE THREAD

**Issue by CEKrause** [opendatacube/datacube-explorer#8]
I had a meeting with a stakeholder yesterday who really wanted to know how many clear observations are available within each scene (not just what scenes are available). 

It would be a useful feature enhancement to add this information to this dashboard.

**Comment by omad** [comment]
Implementing this exactly as requested would require the 'clear' pixel count to be recorded as metadata against each dataset, which isn't something that is done, and isn't even meaningful in a lot of cases.

Digital Earth Australia's recent ARD products do include a cloud cover percentage for each scene, which is possible to view and search for using Explorer.

![image](https://user-images.githubusercontent.com/108979/181699748-fc082245-23dd-4d27-aa9c-c11137d23c12.png)
Ref: https://explorer.sandbox.dea.ga.gov.au/products/ga_ls8c_ard_3/datasets/4b1c218e-47a8-4e23-865f-5b6d6d648327

![image](https://user-images.githubusercontent.com/108979/181699765-cdc41b7f-06b1-4367-8a96-39f7850f92dc.png)
