### ISSUE TITLE
Add DE Africa Logo

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-explorer#87]
Current theme uses Australia Branding for Africa.

![image](https://user-images.githubusercontent.com/491396/75411355-15cba480-5973-11ea-839f-b31ecfcb5645.png)

Africa specific assets [here](https://intranet.ga.gov.au/everyday-tasks/communication-and-design/templates/priority-projects/Digital-Earth-Africa_DE-Africa.ZIP)

**Comment by alexgleith** [comment]
This was fixed in #88
