### ISSUE TITLE
Tests take far too long to run

### ISSUE THREAD

**Issue by alexgleith** [opendatacube/datacube-explorer#94]
21 minutes on GitHub Actions to do a Docker build and run tests.

Docker build needs caching, which should happen soon. But the tests are very slow... so we should fix the slow tests!

**Comment by whatnick** [comment]
Implement pytest cache and incremental testing : https://pytest-incremental.readthedocs.io/

**Comment by alexgleith** [comment]
I think this was resolved by using Kirill's geobase...
