### ISSUE TITLE
Fix _prepare_from_string

### ISSUE THREAD

**Issue by NikitaGandhi** [opendatacube/datacube-explorer#97]
Review and fix _prepare_from_string for following warning:

/usr/local/lib/python3.6/dist-packages/pyproj/crs.py:77: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.
  return _prepare_from_string(" ".join(pjargs))

**Comment by jeremyh** [comment]
Fixed indirectly by 2245b3402ed159c6ee898277384a85c4f96e12d2
